# ===== Server =====
server.port=8080

# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://150.95.24.79:5432/thaitheatre
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP (ปรับตามสเปคเครื่องได้)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-API

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===== JSON =====
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# ===== CORS (แก้ origin ให้ตรงกับ Frontend ของคุณ) =====
app.cors.allowed-origins=http://localhost:4200

# ===== JWT =====
app.jwt.secret=replace-this-with-32+chars-strong-secret
app.jwt.exp-minutes=60

# Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nathaphong2541@gmail.com
spring.mail.password=kmrcbzsnztwynfue
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# token expiry (นาที)
app.reset-token.exp-minutes=60

# frontend base url (ใช้เซ็ตลิงก์ในอีเมล)
app.frontend.base-url=https://your-frontend-domain
app.cookie.secure=false
app.cookie.max-age-seconds=7200